### ISSUE TITLE
I can't use Twiml on calls

### ISSUE THREAD

**Issue by SharksT** [leshow/twilio#3]
There is only the possibility of using a url to make a call, whats the point of have a twiml constructor if i can't use it ? Or it is some other way to use it ?

**Comment by leshow** [comment]
Of course you can use it. If you were writing a server and you wanted to respond to calls with twiml, you could use the library to generate that for you.

If there's some other functionality you'd like `twilio-async` to provide, you're welcome to make a suggestion or (preferably) a PR.

As I understand it, twiml isn't used for making 'calls', it's used for webhooks. https://www.twilio.com/docs/usage/webhooks
