### ISSUE TITLE
method not found in ....

### ISSUE THREAD

**Issue by 4parsleythelion** [leshow/twilio#4]
Hello,

I trying to use twilio-async and the following code:

```
fn twiml_response() {
    let resp = Response::new()
        .say("Hello World")
        .play("https://api.twilio.com/Cowbell.mp3")
        .build();
}
```
gives me an error: .build();
   |          ^^^^^ method not found in `twiml::response::Response<'_>`

Do you have any ideas? Sorry to be a pain.

Ashley

**Comment by leshow** [comment]
Hey, sorry I didn't get a notification for this, can you paste a full code example, there's a test for that piece of code in `twiml/src/lib.rs`, so I'm not sure what wouldn't be compiling.

edit: Oh, I'd bet you forgot to import `twiml::Twiml`, it's the trait that defines `build`. If you post the full error message it probably even tells you that.

**Comment by leshow** [comment]
If you have a different error, feel free to re-open this.
